import matplotlib.pyplot as plt
import numpy as np

# -------------------------------------------------
# Hardcoded categorical data (GT vs extraction)
# -------------------------------------------------

# This file was used to get the categorical comparaison plot for the thesis.
# This is hardcoded here, but the data was taken from the CSV and JSON files generated by the benchmark pipeline.


categories = ["0 - 10", "11 - 20", "21 - 30", "31 - 40", "41 - 50"]

# Ground Truth values (from CSV)
gt_values = [
    0.0927,  # 0 - 10
    0.0636,  # 11 - 20
    0.0774,  # 21 - 30
    0.1314,  # 31 - 40
    0.3351,  # 41 - 50
]

# Gemini extracted values (from JSON)
extracted_values = [
    0.09,   # 0 - 10
    0.065,  # 11 - 20
    0.08,   # 21 - 30
    0.13,   # 31 - 40
    0.34,   # 41 - 50
]

# -------------------------------------------------
# Plot
# -------------------------------------------------
if __name__ == "__main__":
    x = np.arange(len(categories))
    width = 0.35

    fig, ax = plt.subplots(figsize=(7, 4))

    ax.bar(x - width / 2, gt_values, width, label="Ground Truth")
    ax.bar(x + width / 2, extracted_values, width, label="Gemini extraction")

    ax.set_xlabel("Testosterone nadir (ng/dL)")
    ax.set_ylabel("10-year metastasis rate")
    ax.set_xticks(x)
    ax.set_xticklabels(categories)

    ax.set_title("Categorical value extraction: Ground Truth vs Gemini")
    ax.legend()

    ax.grid(axis="y", linestyle="--", alpha=0.4)

    plt.tight_layout()
    plt.savefig("categorical_comparison.png", dpi=200)
    plt.close()

    print("Saved figure: categorical_comparison.png")
